name: Delete Pull Request Deployment
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
   
env:
  PR_REPO_NAME: sc-preview-${{ github.event.pull_request.head.ref }}

jobs:
  delete-page-host:
    runs-on: ubuntu-latest
    steps:
      - name: Delete repository for temporary deployment
        uses: octobay/delete-repository-action@v1
        with:
          name: TomZhaoJobadder/${{ env.PR_REPO_NAME }}
          access-token: ${{ secrets.PAT }}