
name: Pull Request Build and Deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main
      - 'DS**'

env:
  PR_REPO_NAME: sc-preview-${{ github.event.pull_request.head.ref }}

jobs:
  Build-deploy-sc-doc-site:
    name: Build sc doc site Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.*'
      - run: | 
          cd githubPagesTest
          yarn install
      - name: build release
        # run: |
        #   yarn build:doc --base-href "/${{ env.PR_REPO_NAME }}/"
        run: |
          cd githubPagesTest
          yarn build
      - name: Upload scales-doc-site
        uses: actions/upload-artifact@v2
        with:
          name: doc-site
          path: githubPagesTest/dist/github-pages-test

  # create-page-host:
  #   runs-on: ubuntu-latest
  #   steps:
      - name: Create new repository for temporary deployment
        uses: octobay/create-repository-action@v1
        with:
          name: ${{ env.PR_REPO_NAME }}
          # org: jobadder
          access-token: ${{ secrets.PAT }}

  # pr-build-deploy:
  #   needs: [BuildS-sc-doc-site, create-page-host]
  #   runs-on: ubuntu-latest
    # environment:
    #   name: pr-preview
    #   url: https://jobadder.github.io/${{ env.PR_REPO_NAME }}/
    # steps:

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com


      - name: Checkout temporary deployment target repo
        uses: actions/checkout@v3
        with:
          repository: TomZhaoJobadder/${{ env.PR_REPO_NAME }}
          path: 'pr-deploy'
          token: ${{ secrets.PAT }}

      - name: Download sc site Artifacts
        uses: actions/download-artifact@v2
        with:
          name: doc-site
          path: pr-build/dist

      - name: Push files to target
        run: |
          cp -r pr-build/dist/* pr-deploy
          cd pr-deploy
          touch .nojekyll
          git add .
          git commit -m $GITHUB_SHA
          git branch -M gh-pages
          git push -u origin gh-pages
