name: Publish release
on:  
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [ closed ]
env: 
  LOG_PATH: 'projects/scripts/site/docs'
  RELEASE_NOTES: ''
  VERSION_NUMBER: ''

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repo
        uses: actions/checkout@v3    

      - name: Get release notes 
        id: release_notes
        run: |
         cd ${{ env.LOG_PATH }}
         echo 'RELEASE_NOTES<<EOF' >> $GITHUB_ENV
         perl -0ne 'print $1 if /##(.*?)##/sg' changelog.en-US.md >> $GITHUB_ENV
         echo 'EOF' >> $GITHUB_ENV

      - name: Get release version number
        id: ver_num
        run: |  
         cd ${{ env.LOG_PATH }}    
         echo 'VERSION_NUMBER<<EOF' >> $GITHUB_ENV
         sed -n '/##/ ,/##/p; /##/q' changelog.en-US.md | sed 's/##/ /' >>  $GITHUB_ENV
         echo 'EOF' >> $GITHUB_ENV

      - name: create release  
        uses: ncipollo/release-action@v1
        with:        
          tag: ${{ env.VERSION_NUMBER }}
          body: ${{ env.RELEASE_NOTES }}
