name: Publish release
on:  
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [ closed ]

env: 
  PATH: '.\projects\scripts\site\docs'

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repo
        uses: actions/checkout@v3

      - name: Get release version number
        id: ver_num
        run: |
         cd ${{ env.PATH }}
         sed -n '/##/ ,/##/p; /##/q' changelog.en-US.md | sed 's/##/ /' >> $VERSION_NUMBER

      - name: Get release notes 
        id: release_notes
        run: |
         perl -0ne 'print $1 if /##(.*?)##/sg' changelog.en-US.md >> $RELEASE_NOTES

      - name: create release  
        uses: ncipollo/release-action@v1
        with:        
          tag: ${{ steps.ver_num.outputs.VERSION_NUMBER }}
          body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
